# https://taskfile.dev

version: '3'

env:
  MAJORVERSION: 0.0.1
  MINORVERSION: 1

tasks:
  clean:
    cmds:
      - rm *deb
  prepare:
    cmds:
      - sudo apt update -y
      - sudo apt install -y 
          ruby-rubygems 
          build-essential 
          debhelper 
          dh-make
          python3
      - sudo gem install fpm
  package:
    cmds:
      - fpm 
          -s dir
          -t deb 
          --log error
          -p rsyslog-local-config-${MAJORVERSION}-${MINORVERSION}-any.deb
          --name rsyslog-local-config
          --version ${MAJORVERSION}
          --architecture all
          --depends rsyslog-kafka
          --depends python3
          --depends python3-psutil
          --depends socat 
          --after-install postinst
          --config-files /etc/rsyslog.d/
          --config-files /etc/systemd/system/
          --description "Deploy local monitoring configuration for rsyslog"
          src/etc/rsyslog.d/=/etc/rsyslog.d/
          src/etc/systemd/system/=/etc/systemd/system/
          src/usr/local/bin/metrics.py=/usr/local/bin/metrics.py
  contents:
    cmds:
      - dpkg -c *deb
  uninstall:
    cmds:
      - sudo dpkg -P rsyslog-local-config
      - sudo systemctl restart rsyslog
  install:
    cmds:
      - sudo dpkg -i rsyslog-local-config-${MAJORVERSION}-${MINORVERSION}-any.deb
